// This file contains the embedded PDF data for testing
// Load this file separately with: ?test or keep the original PDF_DATA commented out

const PDF_DATA_TEST = {
  meet: 'ThunderRidge Invitational',
  date: '2026-03-14',
  girls: [
    {num:1,name:'Sophie Dinse',school:'SUMMIT'},
    {num:2,name:'Megan Moore',school:'WIDEFIELD'},
    {num:3,name:'Emma Wilson',school:'ALEXANDER'},
    {num:4,name:'Olivia Brown',school:'CHERAW'},
    {num:5,name:'Ava Davis',school:'CHEYENNE'},
    {num:6,name:'Isabella Garcia',school:'HARRISON'},
    {num:7,name:'Mia Rodriguez',school:'KODACHROME'},
    {num:8,name:'Charlotte Martinez',school:'KIOWA'},
    {num:9,name:'Amelia Hernandez',school:'LAKEWOOD'},
    {num:10,name:'Harper Lopez',school:'LIBERTY'},
    {num:11,name:'Evelyn Gonzalez',school:'MANITOU'},
    {num:12,name:'Abigail Perez',school:'MARSTON'},
    {num:13,name:'Emily Flores',school:'MEEKER'},
    {num:14,name:'Elizabeth Rivera',school:'MITCHELL'},
    {num:15,name:'Mila Jackson',school:'MONUMENT'},
    {num:16,name:'Ella White',school:'MORRISON'},
    {num:17,name:'Avery Harris',school:'MOUNTAIN'},
    {num:18,name:'Scarlett Clark',school:'MURPHY'},
    {num:19,name:'Victoria Lewis',school:'NATHROP'},
    {num:20,name:'Madison Walker',school:'NEW CASTLE'},
    {num:21,name:'Luna Hall',school:'PALMER'},
    {num:22,name:'Zoe Allen',school:'PARK'},
    {num:23,name:'Grace Young',school:'PARLIN'},
    {num:24,name:'Chloe King',school:'PEYTON'},
    {num:25,name:'Penelope Wright',school:'PIKEVIEW'},
    {num:26,name:'Leah Patel',school:'PINE'},
    {num:27,name:'Riley Davis',school:'PONDEROSA'},
    {num:28,name:'Nora Miller',school:'PUEBLO'},
    {num:29,name:'Eleanor Wilson',school:'RAMAH'},
    {num:30,name:'Aria Moore',school:'RIDGELINE'},
    {num:31,name:'Stella Taylor',school:'RINDGES'},
    {num:32,name:'Aurora Anderson',school:'ROCKY FORD'},
    {num:33,name:'Luna Thomas',school:'SEDALIA'},
    {num:34,name:'Lily Jackson',school:'SIERRA'},
    {num:35,name:'Scarlett Walters',school:'SIMLA'}
  ],
  boys: [
    {num:1,name:'Liam Smith',school:'SUMMIT'},
    {num:2,name:'Noah Johnson',school:'WIDEFIELD'},
    {num:3,name:'Oliver Williams',school:'ALEXANDER'},
    {num:4,name:'Elijah Brown',school:'CHERAW'},
    {num:5,name:'James Jones',school:'CHEYENNE'},
    {num:6,name:'Benjamin Garcia',school:'HARRISON'},
    {num:7,name:'Lucas Miller',school:'KODACHROME'},
    {num:8,name:'Mason Davis',school:'KIOWA'},
    {num:9,name:'Logan Wilson',school:'LAKEWOOD'},
    {num:10,name:'Ethan Moore',school:'LIBERTY'},
    {num:11,name:'Alexander Taylor',school:'MANITOU'},
    {num:12,name:'Jacob Anderson',school:'MARSTON'},
    {num:13,name:'Michael Thomas',school:'MEEKER'},
    {num:14,name:'Daniel Jackson',school:'MITCHELL'},
    {num:15,name:'Matthew White',school:'MONUMENT'},
    {num:16,name:'David Harris',school:'MORRISON'},
    {num:17,name:'Joseph Clark',school:'MOUNTAIN'},
    {num:18,name:'Samuel Lewis',school:'MURPHY'},
    {num:19,name:'Benjamin Walker',school:'NATHROP'},
    {num:20,name:'James Hall',school:'NEW CASTLE'},
    {num:21,name:'Charles Allen',school:'PALMER'},
    {num:22,name:'Michael Young',school:'PARK'},
    {num:23,name:'Robert King',school:'PARLIN'},
    {num:24,name:'John Wright',school:'PEYTON'},
    {num:25,name:'Richard Patel',school:'PIKEVIEW'},
    {num:26,name:'Joseph Davis',school:'PINE'},
    {num:27,name:'Thomas Miller',school:'PONDEROSA'},
    {num:28,name:'Christopher Wilson',school:'PUEBLO'},
    {num:29,name:'Daniel Moore',school:'RAMAH'},
    {num:30,name:'Matthew Taylor',school:'RIDGELINE'},
    {num:31,name:'Anthony Anderson',school:'RINDGES'},
    {num:32,name:'Mark Thomas',school:'ROCKY FORD'},
    {num:33,name:'Donald Jackson',school:'SEDALIA'},
    {num:34,name:'Steven Walters',school:'SIERRA'},
    {num:35,name:'Paul Rodriguez',school:'SIMLA'},
    {num:36,name:'Andrew Martinez',school:'SODA SPRINGS'},
    {num:37,name:'Joshua Hernandez',school:'SOPRIS'},
    {num:38,name:'Kenneth Lopez',school:'SOTO'},
    {num:39,name:'Kevin Gonzalez',school:'SPACE'},
    {num:40,name:'Brian Perez',school:'SPARKS'},
    {num:41,name:'George Flores',school:'SPECIMEN'},
    {num:42,name:'Edward Rivera',school:'SPINNEY'},
    {num:43,name:'Ronald Jackson',school:'STACE'},
    {num:44,name:'Timothy White',school:'STICKNEY'},
    {num:45,name:'Jason Harris',school:'STRASBURG'},
    {num:46,name:'Jeffrey Clark',school:'SUGAR CITY'}
  ]
};

// Set PDF_DATA to empty by default, or test data if ?test parameter is present
let PDF_DATA = { meet: '', date: '', girls: [], boys: [] };

// Check if URL contains ?test parameter
if (window.location.search.includes('test')) {
  PDF_DATA = PDF_DATA_TEST;
}
